# Generated by Django 5.2.3 on 2025-07-12 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='update_at',
        ),
    ]
